### ISSUE TITLE
Not build with  ota-shadow

### ISSUE THREAD

**Issue by MydevOnline** [tripflex/wifi-captive-portal#8]
if added 
  - origin: https://github.com/mongoose-os-libs/ota-shadow
build frozen  on ota-shadow

platform: esp8266

![screen shot 2018-09-09 at 00 31 08](https://user-images.githubusercontent.com/34922566/45258814-b026d980-b3c7-11e8-8e4c-d8898e75a43e.png)

**Comment by tripflex** [comment]
But this builds fine if you remove my lib?  I've had this happen before, sometimes you have to make sure to do a `--clean` build, or even remove the entire `deps` and `build` directory and try again
